# config = {
#     "LR": 1e-3,
#     "NUM_ENVS": 64,
#     "NUM_STEPS": 300,
#     "TOTAL_TIMESTEPS": 5e7,
#     "UPDATE_EPOCHS": 4,
#     "NUM_MINIBATCHES": 4,
#     "GAMMA": 0.99,
#     "GAE_LAMBDA": 0.95,
#     "CLIP_EPS": 0.2,
#     "ENT_COEF": 2e-6,
#     "VF_COEF": 4.5,
#     "MAX_GRAD_NORM": 0.5,
#     "ACTIVATION": "tanh",
#     "HSIZE": 64,
#     "CONTINUOUS": True,
#     "ANNEAL_LR": True,
#     "DEBUG": False,
# } MABrax

config = {
    "LR": 2.5e-4,
    "NUM_ENVS": 16,
    "NUM_STEPS": 128,
    "TOTAL_TIMESTEPS": 1e7,
    "UPDATE_EPOCHS": 4,
    "NUM_MINIBATCHES": 4,
    "GAMMA": 0.99,
    "GAE_LAMBDA": 0.95,
    "CLIP_EPS": 0.05,
    "ENT_COEF": 0.01,
    "VF_COEF": 0.5,
    "MAX_GRAD_NORM": 0.5,
    "ACTIVATION": "tanh",
    "HSIZE": 64,
    "CONTINUOUS": True,
    "ANNEAL_LR": True,
    "DEBUG": True,
} # MPE
