# config = {
#     "LR": 5e-4,
#     "NUM_ENVS": 16,
#     "NUM_STEPS": 128,
#     "FC_DIM_SIZE": 128,
#     "GRU_HIDDEN_DIM": 128,
#     "TOTAL_TIMESTEPS": 1e7,
#     "UPDATE_EPOCHS": 4,
#     "NUM_MINIBATCHES": 2,
#     "GAMMA": 0.99,
#     "GAE_LAMBDA": 0.95,
#     "CLIP_EPS": 0.3,
#     "ENT_COEF": 0.01,
#     "VF_COEF": 1.0,
#     "MAX_GRAD_NORM": 0.5,
#     "ACTIVATION": "tanh",
#     "ANNEAL_LR": True,
#     "DEBUG": True,
#     "GET_AVAIL_ACTIONS": False
# } # MPE

config = {
    "LR": 0.004,
    "NUM_ENVS": 128,
    "NUM_STEPS": 128,
    "GRU_HIDDEN_DIM": 128,
    "FC_DIM_SIZE": 128,
    "TOTAL_TIMESTEPS": 1e7,
    "UPDATE_EPOCHS": 4,
    "NUM_MINIBATCHES": 4,
    "GAMMA": 0.99,
    "GAE_LAMBDA": 0.95,
    "CLIP_EPS": 0.05,
    "ENT_COEF": 0.01,
    "VF_COEF": 0.5,
    "MAX_GRAD_NORM": 0.25,
    "ACTIVATION": "relu",
    "ANNEAL_LR": True,
    "DEBUG": False,
    "GET_AVAIL_ACTIONS": True,
    "DONT_VMAP": True
} # SMAX
